"""Initial schema

Revision ID: 8d254e1f35f7
Revises: 
Create Date: 2025-12-31 02:46:24.917032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d254e1f35f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name_ja', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('profiles',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'INSTRUCTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_table('courses',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('title_ja', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('category_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('instructor_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_category_id'), 'courses', ['category_id'], unique=False)
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_courses_is_published'), 'courses', ['is_published'], unique=False)
    op.create_table('course_comments',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('course_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_instructor_reply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_comments_course_id'), 'course_comments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_comments_user_id'), 'course_comments', ['user_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('course_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('title_ja', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_course_order', 'videos', ['course_id', 'order_number'], unique=False)
    op.create_index(op.f('ix_videos_course_id'), 'videos', ['course_id'], unique=False)
    op.create_table('video_progress',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('video_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video')
    )
    op.create_index(op.f('ix_video_progress_user_id'), 'video_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_progress_video_id'), 'video_progress', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_progress_video_id'), table_name='video_progress')
    op.drop_index(op.f('ix_video_progress_user_id'), table_name='video_progress')
    op.drop_table('video_progress')
    op.drop_index(op.f('ix_videos_course_id'), table_name='videos')
    op.drop_index('idx_course_order', table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_course_comments_user_id'), table_name='course_comments')
    op.drop_index(op.f('ix_course_comments_course_id'), table_name='course_comments')
    op.drop_table('course_comments')
    op.drop_index(op.f('ix_courses_is_published'), table_name='courses')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_category_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
